# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Arrays" data-toc-modified-id="Arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Arrays</a></div><div class="lev1 toc-item"><a href="#多次元配列" data-toc-modified-id="多次元配列-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>多次元配列</a></div><div class="lev1 toc-item"><a href="#配列の初期化" data-toc-modified-id="配列の初期化-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>配列の初期化</a></div><div class="lev1 toc-item"><a href="#配列の情報を取るための関数" data-toc-modified-id="配列の情報を取るための関数-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>配列の情報を取るための関数</a></div><div class="lev1 toc-item"><a href="#配列の操作" data-toc-modified-id="配列の操作-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>配列の操作</a></div><div class="lev1 toc-item"><a href="#配列上の演算" data-toc-modified-id="配列上の演算-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>配列上の演算</a></div>

# Arrays

In [1]:
# まずは普通に配列を定義。
# この指定の仕方はPythonとも同じ。
fruits = ["Apple", "Orange", "Banana"]

3-element Array{String,1}:
 "Apple" 
 "Orange"
 "Banana"

In [2]:
# 数字が混ざっていても大丈夫
fruits_num = ["Apple", 1, "Orange", 2, "Banana"]

5-element Array{Any,1}:
  "Apple" 
 1        
  "Orange"
 2        
  "Banana"

In [3]:
# 要素の取得
# indexはPythonとは違って1始まりなので、注意。
fruits[1]

"Apple"

In [4]:
# 0を指定するとエラーになる
fruits[0]

LoadError: BoundsError: attempt to access 3-element Array{String,1} at index [0]

In [5]:
# pushとpopもできる
push!(fruits, "Peach")
println(fruits)
pop!(fruits)
println(fruits)

String["Apple", "Orange", "Banana", "Peach"]
String["Apple", "Orange", "Banana"]


In [6]:
# 要素にアクセスして情報も更新できる
fruits[1] = "Apple2"
fruits

3-element Array{String,1}:
 "Apple2"
 "Orange"
 "Banana"

# 多次元配列

In [7]:
# もちろん、これも普通にできる
fruits_2d = [["Apple", "Orange", "Banana"], ["Apple", "Orange", "Banana", "Peach"]]

2-element Array{Array{String,1},1}:
 String["Apple", "Orange", "Banana"]         
 String["Apple", "Orange", "Banana", "Peach"]

In [8]:
# 乱数で生成とかも。モジュールのインポートとかしなくていいのが、Pythonとの違いだなと笑
rand(4,3)

4×3 Array{Float64,2}:
 0.445258  0.587788  0.996786  
 0.522811  0.743046  0.00644533
 0.99362   0.325897  0.536397  
 0.831977  0.433696  0.300295  

# 配列の初期化

ここでは、Arrayを作成するときに使う関数をまとめます。痒いところに手が届く関数が多くて素晴らしい…。

【参考】
- [Multi-dimensional Arrays](https://docs.julialang.org/en/stable/manual/arrays/)
- [Arrays](https://docs.julialang.org/en/stable/stdlib/arrays/)

In [9]:
# numpyとかで配列を初期化するときによく使うzeros
# 普通の1d-array
println(zeros(5))

# 多次元配列も可能
println(zeros(2,4))

# 型の指定もできる
println(zeros(Int8, 2,4))

# 型の変換もできるみたい
# 出力が、「0 => 0.0」 となっているのに注目
zeros_array = zeros(Int8, 2,4)
println(zeros(zeros_array, Float64))

[0.0, 0.0, 0.0, 0.0, 0.0]
[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]
Int8[0 0 0 0; 0 0 0 0]
[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]


In [10]:
# onesもある。似たような感じで使える。
# 普通の1d-array
println(ones(5))

# 多次元配列も可能
println(ones(2,4))

# 型の指定もできる
println(ones(Int8, 2,4))

# 型の変換もできる
ones_array = ones(Int8, 2,4)
println(ones(ones_array, Float64))

[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
Int8[1 1 1 1; 1 1 1 1]
[1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]


上の関数以外にも似たものとして、`trues` とか `falses` とかがあるっぽく、似たような感じで使える

In [11]:
# 0や1, trueやfalse以外の値を入れたい場合は、fill関数を使うと良いっぽい。
fill(10, (3,2))

3×2 Array{Int64,2}:
 10  10
 10  10
 10  10

# 配列の情報を取るための関数

配列の長さとかサイズとかを配列を操作するときには見ると思うのですが、そのあたりの関数をまとめます。


In [12]:
# ここではこの配列を例にします
ones_2d = ones(2,3)

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [13]:
# 配列のdimentionを取得
ndims(ones_2d)

2

In [14]:
# indexを取得する関数
indices(ones_2d)

(Base.OneTo(2), Base.OneTo(3))

In [15]:
# 長さ、、、ではなくて、要素の数を取得する関数であることに注意。
# Pythonのlenとは違う
length(ones_2d)

6

In [16]:
# 要素へのインデックスをiterableな形で取得してくれる方法がある
# それが以下。
eachindex(ones_2d)

Base.OneTo(6)

In [17]:
# こんな感じで呼び出せる。以下は、for文の例。
# ドキュメントを斜め読みした感じでは、早いらしい。
for iter in eachindex(ones_2d)
    println(iter, "=>", ones_2d[iter])
end

1=>1.0
2=>1.0
3=>1.0
4=>1.0
5=>1.0
6=>1.0


In [18]:
# non-zeroな要素の数を返してくれる関数。
# 以下だと、6と返ってくる
countnz(ones_2d)

6

# 配列の操作

reshapeや配列の結合など、配列に加える操作周りの方法。

In [19]:
# reshape
ones_1d = ones(16)
reshape(ones_1d, (4,4))

4×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [20]:
# 片方の次元だけ指定するパターンも可能
reshape(ones_1d, 2, :)

2×8 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [21]:
# でもちゃんとreshapeできないとだめ。
# 例えば、3とか指定するとだめ。
reshape(ones_1d, 3, :)

LoadError: DimensionMismatch("array size 16 must be divisible by the product of the new dimensions (3, Colon())")

In [22]:
# verticalな方向に結合する
a = [1 2 3 4 5]
b = [6 7 8 9 10; 11 12 13 14 15]
vcat(a, b)

3×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15

In [23]:
# Horizontalな方向に結合する
a = [1; 2; 3; 4; 5;]
b = [6; 7; 8; 9; 10;]
hcat(a, b)

5×2 Array{Int64,2}:
 1   6
 2   7
 3   8
 4   9
 5  10

# 配列上の演算

In [24]:
# 全体に1足したいとかはこれでできる。
a = [1 2 3 4 5]
println(a + 1)
println(a - 1)
println(a * 2)
println(a / 2)

[2 3 4 5 6]
[0 1 2 3 4]
[2 4 6 8 10]
[0.5 1.0 1.5 2.0 2.5]


In [25]:
# 累積演算は以下のような感じ。
accumulate(+, [1,2,3])

3-element Array{Int64,1}:
 1
 3
 6

In [26]:
# 真ん中に値を挟むと、その値が最初の演算に使われる。
# 以下の例であれば、100+1が最初に出てくる。
accumulate(+, 100, [1,2,3])

3-element Array{Int64,1}:
 101
 103
 106

In [27]:
accumulate(min, 0, [1,2,-1])

3-element Array{Int64,1}:
  0
  0
 -1

他にもたくさんあるが、ここまでで。他の例は[こちら](https://docs.julialang.org/en/stable/stdlib/arrays/)見れる。